### PR TITLE
Fix for large maxByteSize

### PR DESCRIPTION
**Pull request by restorer**
(larger than int can contain)

### CODE REVIEW

**Comment by wdelfuego** [comment]
Thanks for your input, restorer!
Could you elaborate a bit on what the problem was? 
I am curious what issue you ran into, and what exactly you mean by "larger than int can contain"
Thanks!

**Comment by restorer** [comment]
Just try `./sqlsplitter really-big-dump.sql 4294967296`

**Comment by wdelfuego** [comment]
I don't have a really big sql dump right now, so I can't test it. In any case, I wouldn't know if what I see is what you saw without knowing what you ran into exactly.
Would you be so kind to elaborate? One or two sentences will do :). Thanks so much!

**Comment by restorer** [comment]
Appears that actually you don't need large sql.

```
echo 'USE test;' > test.sql
./sqlsplitter test.sql 4294967296
```

Result:

```
Good to go! Will split (test.sql to a maximum of 0 bytes
Will write part[0] to [00000]test.sql

00000[=================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================
```

It continues to print `=` infinitely.

Problem is in `atoi` function, that converts given string to integer (32 bits, signature - `int atoi(const char *nptr)`, man - https://linux.die.net/man/3/atoi).

But 4294967296 (and larger values) has more than 32 bits, so these values doesn't fit in integer (32 bits).

Example code:

```
#include <iostream>
#include <cstdlib>

int main(int argc, char * const argv[]) {
	std::cout << "4294967296 -> " << atoi("4294967296") << "\n";
	std::cout << "4294967297 -> " << atoi("4294967297") << "\n";
	std::cout << "4294967298 -> " << atoi("4294967298") << "\n";

	return 0;
}
```

Output:

```
4294967296 -> 0
4294967297 -> 1
4294967298 -> 2
```

But `atol` converts string to long, which has more than 32 bits (on 64-bit processors). Following code:

```
#include <iostream>
#include <cstdlib>

int main(int argc, char * const argv[]) {
	std::cout << "4294967296 -> " << atol("4294967296") << "\n";
	std::cout << "4294967297 -> " << atol("4294967297") << "\n";
	std::cout << "4294967298 -> " << atol("4294967298") << "\n";

	return 0;
}
```

Returns correct result:

```
4294967296 -> 4294967296
4294967297 -> 4294967297
4294967298 -> 4294967298
```

**Comment by wdelfuego** [comment]
Thank you so much for your elaborate explanation and your pull request, merging now

**Pull request merged**
